/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


#define AGENDA 1
#define AGENDA_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define divisa 1
extern  float * divisa_1(float *, CLIENT *);
extern  float * divisa_1_svc(float *, struct svc_req *);
extern int agenda_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define divisa 1
extern  float * divisa_1();
extern  float * divisa_1_svc();
extern int agenda_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
