/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

double *
exchange_virtual_1_svc(struct exchange_service *argp, struct svc_req *rqstp)
{
	static double  result;

	int option_menu;
	double exchange_coin;

	option_menu = argp->option_menu;
	exchange_coin = argp->exchange_coin;

	switch (option_menu)
	{
	case 1:
		result = exchange_coin*(0.0013);
	break;

	case 2:
		result = exchange_coin*(0.0011);
	break;

	case 3:
		result = exchange_coin*(0.013);
	break;

	case 4:
		result = exchange_coin*(0.00097);
	break;

	case 5:
		result = exchange_coin*(0.0072);
	break;
	
	default:
		result = exchange_coin*(0.0099);
	break;
	}

	return &result;
}

char *
virtual_notebook_1_svc(struct virtual_service *argp, struct svc_req *rqstp)
{
	static char  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char *
calendary_virtual_1_svc(struct calendary_service *argp, struct svc_req *rqstp)
{
	static char  result;

	/*
	 * insert server code here
	 */

	return &result;
}

char *
postit_virtual_1_svc(struct postit_service *argp, struct svc_req *rqstp)
{
	static char  result;

	/*
	 * insert server code here
	 */

	return &result;
}
