/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"

float *
exchange_1_svc(struct exchange_t *argp, struct svc_req *rqstp)
{
	//coin_exchange = moneda a cambiar
	//menu_option = opción que vendrá del menu principal
	float coin_exchange = argp->coin_exchange;
	int menu_option = argp->menu_option;

	//check_exchange = moneda ya cambiada
	float check_exchange;
	static float  result;

	if (menu_option==1)
	{
		// CLP to DOLAR
		check_exchange = (coin_exchange*798,60);
		result = check_exchange;
	}

	if (menu_option==2)
	{
		// CLP to EURO
		check_exchange = (coin_exchange*937,24);
		result = check_exchange;
	}
		

	return &result;
}
