/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "main.h"

bool_t
xdr_exchange_t (XDR *xdrs, exchange_t *objp)
{
	register int32_t *buf;

	 if (!xdr_float (xdrs, &objp->coin_exchange))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->menu_option))
		 return FALSE;
	return TRUE;
}
